### ISSUE TITLE
Fix Remaining Indexing server on ESOC West

### ISSUE THREAD

**Issue by concolato** [USStateDept/search#111]
Left over from task #15

**Comment by jpower23** [comment]
includes reboot and some indexing since I tried just reseting and it did not work.

**Comment by jpower23** [comment]
Almost done, got one more working today.

**Comment by jpower23** [comment]
found issue while testing GUI updates. One of the indexers is not grabbing titles for the content, working to fix it

**Comment by jpower23** [comment]
Indexers are set up going to close this out and create new ones if/as I find errors.
