### ISSUE TITLE
Implement Results for .NET Process form SIO for Sharepoint Federation for Search

### ISSUE THREAD

**Issue by concolato** [USStateDept/search#14]

**Comment by jpower23** [comment]
Contacted Thomas O'Mara about working with one of thier developers to get a client app developed that we can use.

**Comment by jpower23** [comment]
Met with Ravi and Jeremy about getting a developer to work on the client app. They may have A Java programmer who can do it. Otherwise it will be a .NET application.  Waiting to hear back from them.
