### ISSUE TITLE
Re-Index Data for ESOC West

### ISSUE THREAD

**Issue by concolato** [USStateDept/search#15]

**Comment by jpower23** [comment]
Having issues with indexing of GAL data. Getting error they say is related to column limits. Working with A Bureau team to get more information.

**Comment by jpower23** [comment]
Going to see if we can use the older GAL fetch, which may not work because of licensing.  We may need to stand up an older IDOL instance to get this completed and then keep working to get the new GAL connector to work.

**Comment by jpower23** [comment]
Older fetch worked to index GAL results. Still making some minor tweaks to other connectors. May have an issue with one of the servers which would require moving some indexing to a different server and may hold up process.

**Comment by jpower23** [comment]
11 is working very slow, We are running one service on it, it will need to be monitored.

**Comment by jpower23** [comment]
Had issues with 3  or 4 servers needing to be rebooted. This will be a big problem if it continues. We will need monitor this. One of the servers was an IDOL server.

**Comment by concolato** [comment]
What is the status for this?

**Comment by jpower23** [comment]
We have re-indexed most data. ONE Connector is having issues. May be related to the Server it is running on - 11 which has problems.

**Comment by concolato** [comment]
Do we want to break this up into two tasks? Perhaps fixing 11 is one and testing the indexing is another?

**Comment by jpower23** [comment]
I've added fix Server 11
