### ISSUE TITLE
Look into automating "I did not find.."

### ISSUE THREAD

**Issue by concolato** [USStateDept/search#3]

**Comment by dstepp** [comment]
Creating a form would be great.

**Comment by concolato** [comment]
Agreed. I can pivot from Terry's sample form.

**Comment by concolato** [comment]
I will build a form based on the one used in TMAT and evaluate against Postgres DB and Solr.

**Comment by concolato** [comment]
I have broken this up into more granular tasks thus finishing up the "Looking into ..." part.
