### ISSUE TITLE
Export IDOL data from DEVLAN/DIN

### ISSUE THREAD

**Issue by jpower23** [USStateDept/search#355]

**Comment by concolato** [comment]
We are in the process of exporting and moving Idol indexed data from our DINs as they contain .sbu URLs. It is a slow process.

**Comment by concolato** [comment]
Export Command: http://localhost:9001/DREEXPORTIDX?FileName=C:\path_to_export_to\file_name.

**Comment by concolato** [comment]
Idol Initialize Command: http://localhost:9001/DREINITIAL?. This resets Idol and deletes all the data.

**Comment by concolato** [comment]
Data From my Idol instance has been removed. Exporting process has completed. Now going to transfer to ON using Jim's Iron Key for further analysis.
