### ISSUE TITLE
Add Bureau Top Match Category

### ISSUE THREAD

**Issue by jpower23** [USStateDept/search#4]
Add a Category to Top Matches for Bureaus. This should mimic the Post Category with some differences.

**Comment by jpower23** [comment]
Altered java and jsp files for creation of Bureau Top Match. Need to set up TMAT code project on DEVLAN, compile and test. This has been put on hold for time being.

**Comment by concolato** [comment]
We may want to break this up since it is at 5.

**Comment by jpower23** [comment]
Need to set up DEV environment for testing.
