### ISSUE TITLE
Explore Method for connecting to SP .NET Client Process

### ISSUE THREAD

**Issue by concolato** [USStateDept/search#73]
Need to find an approach for connecting to SharePoint (SP) Client with Java so as to return an XML object from SP Client into Java handler.

**Comment by concolato** [comment]
It seems that this can only be accomplished using a bridge, which is an additional library. We are looking into another way using Java directly.

**Comment by jpower23** [comment]
This would most likely require a bridge which may be something that would require ITCCB  approval.
