### ISSUE TITLE
Left side filtering issues in production

### ISSUE THREAD

**Issue by jpower23** [USStateDept/search#91]
PROD: When using the left side filters, the filtered search only works for the first page. when advancing to the second page the filter is removed.

**Comment by concolato** [comment]
I am actually noticing that these do not seem to work at all on Prod.

**Comment by concolato** [comment]
This is dependent on task #92, which involved synchronizing Idol configs and re-indexing.

**Comment by concolato** [comment]
This has been fixed and was caused by Java Script errors.
